# Generated by Django 5.2.7 on 2025-11-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='hora_inicio',
        ),
    ]
