# Generated by Django 5.2.7 on 2025-11-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_medicamento_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='altura_cm',
            field=models.FloatField(blank=True, help_text='Altura en centímetros.', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_actividad',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('ligero', 'Actividad ligera (1-3 veces/semana)'), ('moderado', 'Actividad moderada (3-5 veces/semana)'), ('intenso', 'Actividad intensa diaria')], help_text='Nivel de actividad física', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='peso_kg',
            field=models.FloatField(blank=True, help_text='Peso en kilogramos.', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True),
        ),
    ]
