# Generated by Django 5.2.7 on 2025-11-12 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_perfilusuario_altura_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='App.medicamento')),
            ],
        ),
    ]
