# Generated by Django 5.2.7 on 2025-11-12 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_registrotoma'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
