# Generated by Django 5.2.7 on 2025-11-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_medicamento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='recordatorio_horas',
            field=models.PositiveIntegerField(default=2, help_text='Cada cuántas horas recordar tomar agua.'),
        ),
    ]
