# Generated by Django 5.2.7 on 2025-11-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_perfilusuario_recordatorio_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_medicamentos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='notificar_resumen_diario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='recordatorio_horas',
            field=models.FloatField(default=2, help_text='Cada cuántas horas recordar tomar agua.'),
        ),
    ]
